### ISSUE TITLE
AttributeError: 'port_scan' object has no attribute '__dict__'. Did you mean: '__dir__'?

### ISSUE THREAD

**Issue by TajangSec** [AlaBouali/bane#12]
When I used Information gathering ->Very Fast port scan, an error occurred and the error content was as follows:
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\lib\site-packages\bane-4.8.4-py3.10.egg\bane\info_s.py", line 422, in __init__
AttributeError: 'port_scan' object has no attribute '__dict__'. Did you mean: '__dir__'?`
![image](https://user-images.githubusercontent.com/63721558/194735313-a6e844a6-a6a0-4a21-a92e-843004520cdd.png)
May I ask why this problem occurs? It should not be caused by my environment.

**Comment by AlaBouali** [comment]
fixed.
