### ISSUE TITLE
How to run/install for kali linux from 0, I'm a beginner :(

### ISSUE THREAD

**Issue by odin032** [AlaBouali/bane#15]
I finished with pip install bane, How to run it now?

**Comment by odin032** [comment]
I finished with pip install bane.

**Comment by odin032** [comment]
How to run it now?

**Comment by AlaBouali** [comment]
installation ( you need to do it once ) :
`sudo pip3 install bane`
or
`sudo pip install bane`

run :
write in your terminal
`python3`
it will run the python's interpreter, then write:
`import bane`

then follow the documentation of any section you want to learn (brute force, ddos, vulnerability scanning...)
I hope this was clear enough !

**Comment by AlaBouali** [comment]
here is an example:

![Capture d’écran 2023-11-11 012552](https://github.com/AlaBouali/bane/assets/28494129/ffc6e2ae-d992-4588-9ab1-743284b92800)
![Capture d’écran 2023-11-11 012806](https://github.com/AlaBouali/bane/assets/28494129/ab327e57-83bd-45fc-92dd-676205607d68)
