### ISSUE TITLE
dosen't work

### ISSUE THREAD

**Issue by maomao976431** [AlaBouali/bane#2]
![image](https://user-images.githubusercontent.com/46959219/54867929-6b8de900-4dc1-11e9-820b-513bf1797ab5.png)
why it's dosen't work?

**Comment by AlaBouali** [comment]
first thank you for giving my library a try, second this you must rename your file with different name than this library's name or any installed python library (sockets, requests, urllib2...), rename it: mao.py or example.
+ the parameter is "port" not "p"
do like i suggested and it will work fine
