### ISSUE TITLE
Add a document with list of commands to execute different things

### ISSUE THREAD

**Issue by BigYashi69** [AlaBouali/bane#20]
**Is your feature request related to a problem? Please describe.**
yes im having trouble 100% figuring out the ddos stystem so a document with commands and instructions would be helpful
**Describe the solution you'd like**
i want to ddos for practice perposes
**Describe alternatives you've considered**
using different program but this one seems the best so far
**Additional context**

**Comment by AlaBouali** [comment]
You need a fundamental understanding of Python programming language to use this module. There are no command-line options, but I am considering adding them soon! Until that time, please follow the documentation's explanations here: https://github.com/AlaBouali/bane/tree/master/bane/ddos on how to run the attacks' simulations of yours. 

Note: NOT RESPONSIBLE FOR ANY ACTIONS YOU PERFORM USING THIS SOFTWARE, NEITHER DO I ENCOURAGE ILLEGAL ACTIVITIES. BY USING THIS SOFTWARE YOU ACCEPT THAT YOU ALONE ARE RESPONSIBLE AND THE PERSON TO HOLD ACCOUNTABLE FOR YOUR ACTIVITIES USING IT AS I, THE DEVELOPER, HAS CREATED THIS FOR EDUCATIONAL PURPOSES ONLY.
