### ISSUE TITLE
No module named orderedmultidict

### ISSUE THREAD

**Issue by elixirop** [AlaBouali/bane#5]
I installed before , but always say no module named orderedmultidict

![image](https://user-images.githubusercontent.com/68217482/110076694-ebb17d00-7d52-11eb-8745-ead2691c4016.png)

![image](https://user-images.githubusercontent.com/68217482/110076864-2d422800-7d53-11eb-9213-42cc1f1686e7.png)

**Comment by AlaBouali** [comment]
1- that's not how you use bane.. you start python interpreter then you import bane and call the functions. Don't clone and run the files !! They are not that kind of scripts.
2- when you run the command "python ddos.py", it's obvious that you are running python2.7. And when you run "pip install ..." it says that the package is installed for python3.9. So try running "python3" and then import bane and call the functions.

Have a good day.

**Comment by elixirop** [comment]
thanks for your answet, could you help to import bane ?  I dont know how to use it , please !

**Comment by AlaBouali** [comment]
Read the "README.MD" file please for the details you asked for !! It is called "READ ME" for a reason :)
