### ISSUE TITLE
WARNING: can't import layer ipsec: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.9/fractions.py)

### ISSUE THREAD

**Issue by jkeridLNX3** [AlaBouali/bane#6]
WARNING: can't import layer ipsec: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.9/fractions.py)

**Comment by jkeridLNX3** [comment]
ty

**Comment by AlaBouali** [comment]
i just checked it out and it's just "warning" related to "kamene" module . It's not something really important nd should be worry about :)
keep using bane and you will find it something neglegeable !
